# Jekyll configuration

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - admin
  - archive.py
  - notes.md

# Note that GitHub Pages does not allow changing the source directory:
# https://help.github.com/en/articles/configuring-jekyll
# Thus many files need to be excluded.

# Site information
title: UW-Madison AIRG
description: >
  Machine learning and artificial intelligence reading group (AIRG) in
  the Computer Sciences Department at the University of Wisconsin -
  Madison

# Default site configuration
defaults:
  - scope:
      path: "" # global scope
    values:
      layout: "default"
